language: java

jdk:
  - openjdk8
  
branches:
  only:
    - master
    - stable-core
    - stable

addons:
  apt:
    packages:
    - libmaven-ant-tasks-java
    
install: true

script: 
  - if [ $TRAVIS_BRANCH == "stable-core" ]; then ant -f build.xml jar-core; fi 
  - if [ $TRAVIS_BRANCH != "stable-core" ]; then ant -f build.xml jar ; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: ant -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -f build.xml  bindist deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ant -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -Drelease=final -f build.xml bindist deploy
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script: ant -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -Drelease=final -f build.xml deploy-core
    on:
      branch: stable-core
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always